### ISSUE TITLE
Browser Testing — Jess

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#81]
# Browser Testing
Welcome to browser testing, @jessjodoin . 

I have assigned you the following list of browsers to test [the website](https://determined-yonath-0381f1.netlify.app/) on. Please check things off as you complete them.

Additionally, please document any concerns you encounter during testing in this issue thread, and include any relevant supporting documentation, including screenshots 🙂 

---
### Desktop
- [x] Chrome on MacBook

---
### Mobile
- [x] Chrome on Android
- [x] Default Android browser 
- [x] Firefox on Android

---
### Checklist for each browser tested:
- [x] Test home page (including student filters)
- [x] Test quiz page
- [x] Test Dawson student page (template 2)
- [x] Test Cole student page (template 4)
- [x] Test Brianna student page (template 1)
- [x] Test Ian student page (template 3)
- [x] Test Jude student page (template 5)
- [x] Test wrong page (to test 404)
—
- [x] Test all screen widths
- [x] Test all screen heights
- [x] Test fullscreen
- [x] Test mobile portrait
- [x] Test mobile landscape
—
- [x] Test with font sizes 2x smaller
- [x] Test with font sizes 2x bigger
- [x] Test with images disabled
- [x] Test with CSS disabled

---
---
---
Deadline: Saturday, March 20th, 11:59PM
---
---
---

**Comment by JessJodoin** [comment]
YELLOOOOOO! So sorry I'm hella late to this 😢 But here it is!

### **Home Page** (_on Chrome web/mobile, Android default_)

- video doesn’t play automatically/at all even if I refreshed. BUT if I clicked the logo in the header to bring it to the homepage (even though I’m on the homepage), it will then play 
- prof cards click to nowhere like a blank page (which is fine, are we still wanting to add a thank you page so like they click to that page or should we just make them not clickable?)
- ‘support’ in footer needs a link (currently just #) 
- with CSS disabled, it’s hella ugly but that’s to be expected LOL (we get gross side-scrolly-ness)


### **Home Page** (_on Android Firefox_)

- video doesn’t play automatically BUT it does give a play button so you can play it and then it will continuously play


### **Quiz Page** (_on all browsers tested - Chrome web/mobile, Android default, Android Firefox_)
- is there a way to reset the quiz so I can stay on that page and keep redoing it?
- ‘book a meeting’ buttons don’t lead to their calendly page but an error page saying the page could not be found and it has your (MacKenzie) name — bulk0002 — in the url. BUT this only happens after you complete the quiz, if you click ‘book a meeting’ before you’ve completed the quiz they go the right place
- with images disabled, no alts show up
- with CSS disabled, we get some weird stuffs happening and I’m not sure what all that ‘uk-size10’ stuff is but if goes on for a while

<img width="599" alt="Screen Shot 2021-03-27 at 2 30 48 PM" src="https://user-images.githubusercontent.com/43217543/112733044-06bb7b00-8f14-11eb-8656-d21842946a49.png">


### **Templates 1, 2, 4, and 5** (_on all browsers tested - Chrome web/mobile, Android default, Android Firefox_)
- on mobile landscape, the buttons are kinda close together (but that’s definitely being nit-picky, they still look and function like they’re supposed to so meh)

<img width="393" alt="Screen Shot 2021-03-27 at 3 10 59 PM" src="https://user-images.githubusercontent.com/43217543/112733081-35d1ec80-8f14-11eb-8284-e00e50cd253f.png">



### **Template 3** (_on Chrome web/mobile, Android default_)
- it’s being a shit but like only on Ian’s, that second project is suuuuper small for no reason. I checked Sabrina’s and mine (because we all have template 3) and the look fine so I dunno why Ian's page specifically is doing that
<img width="955" alt="Screen Shot 2021-03-27 at 2 39 17 PM" src="https://user-images.githubusercontent.com/43217543/112733103-5306bb00-8f14-11eb-9bc0-fb18b58e1374.png">

- with images disabled, again, it’s being a shit for Ian’s lol though the alt tags on the headshots for some colours is hard to read (will probably just have to add a default black to the alt tags or something)
<img width="1537" alt="Screen Shot 2021-03-27 at 2 44 10 PM" src="https://user-images.githubusercontent.com/43217543/112733121-729de380-8f14-11eb-9ed6-3e4189dc793b.png">

<img width="475" alt="Screen Shot 2021-03-27 at 2 46 34 PM" src="https://user-images.githubusercontent.com/43217543/112733122-75003d80-8f14-11eb-9876-c2272e06fd5e.png">

- on mobile portrait (for Ian only cause apparently our site hates Ian’s page LOL) the ‘to top’ button isn’t overlaying on top like it typically does (on the other templates and other template 3s) so we get side-scrolly-business
- on mobile landscape (again only for Ian) it like completely ignores the media queries can get super big and zoomed in… ’tis quite strange

### **Template 3** (_on Android Firefox_)
- IT’S NOT BEING AN ASSHOLE WOOO! F YOU CHROME AND THE DUMB DEFAULT ONE!! (what I mean is none of the issues mentioned for Chrome and Android default are happening with Firefox lol)


### **404 Page** (_on all browsers tested - Chrome web/mobile, Android default, Android Firefox_)
- so… I definitely did it wrong lol but I watched Thomas’ tutorial/followed the learn the web lesson so I dunno :( but I know it looks cute LOL (so we’ll just have to fix it so it displays)
