### ISSUE TITLE
Browser Testing — Jen

### ISSUE THREAD

**Issue by MacKenzieRose** [algonquindesign-grads/2021#82]
# Browser Testing
Welcome to browser testing, @jen-power . 

I have assigned you the following list of browsers to test [the website](https://determined-yonath-0381f1.netlify.app/) on. Please check things off as you complete them.

Additionally, please document any concerns you encounter during testing in this issue thread, and include any relevant supporting documentation, including screenshots 🙂 

---
### Desktop
- [ ] Edge on MacBook
- [ ] Safari on MacBook
- [ ] Internet Explorer on MacBook

---
### Mobile
- [ ] Safari on iPhone5

---
### Checklist for each browser tested:
- [ ] Test home page (including student filters)
- [ ] Test quiz page
- [ ] Test Dawson student page (template 2)
- [ ] Test Cole student page (template 4)
- [ ] Test Brianna student page (template 1)
- [ ] Test Ian student page (template 3)
- [ ] Test Jude student page (template 5)
- [ ] Test wrong page (to test 404)
—
- [ ] Test all screen widths
- [ ] Test all screen heights
- [ ] Test fullscreen
- [ ] Test mobile portrait
- [ ] Test mobile landscape
—
- [ ] Test with font sizes 2x smaller
- [ ] Test with font sizes 2x bigger
- [ ] Test with images disabled
- [ ] Test with CSS disabled

---
---
---
Deadline: Saturday, March 20th, 11:59PM
---
---
---

**Comment by jen-power** [comment]
@MacKenzieRose 
Here are a list of things I flagged:

-The main hero banner/animation looks way too far down the page, some of the content goes below the fold and there’s a lot of white space at the top. I think this could be smaller, there is a LOT of scrolling before you even see the students. It needs to have a smaller max-width.

-The Book a Meeting button in the Results section for the quiz is the same for every person and it looks like it’s MacKenzie’s link (/bulk0002)

-From a web point-of-view, having a navigation tab called Support but it being for the profs seems confusing (i.e. it’s not web support and they’re also referred to as mentors on the home page)

-Project 2 on Template 3 looks like there’s a grid issue (at least on Ian’s page). The text takes up way more space than the project image.
<img width="1675" alt="Screen Shot 2021-03-17 at 9 57 13 PM" src="https://user-images.githubusercontent.com/43247074/111561998-c9b0f500-876b-11eb-9e71-fd094c247fa5.png">

-Page Not Found exists but isn’t styled with the branding.

-At 2x text-size in Edge the first set of buttons (portfolio and meeting) bump into each other between small and medium screen sizes. Probably not a huge issue. These buttons also bump into each other at 100% in Safari between the same sizes.
<img width="649" alt="Screen Shot 2021-03-17 at 9 58 15 PM" src="https://user-images.githubusercontent.com/43247074/111562083-ef3dfe80-876b-11eb-8d91-bbdd647aec4b.png">

-Upon opening the website for the first time in a new browser, the homepage loads really slow, so it’s basically blank due to the large animation that plays.

-In Safari I can see a small white line in the “Looking for a Designer?” Section on the homepage, between the div that holds the text and the arrow at the bottom.
<img width="731" alt="Screen Shot 2021-03-17 at 9 59 25 PM" src="https://user-images.githubusercontent.com/43247074/111562150-10065400-876c-11eb-944c-9635d5e8be4b.png">

On Safari & iPhone 5, on Jude’s profile, their specialities (Illustration, Motion, Branding) are super squished together, it looks like one word.
<img width="281" alt="Screen Shot 2021-03-17 at 10 00 16 PM" src="https://user-images.githubusercontent.com/43247074/111562227-34fac700-876c-11eb-88a8-7c68012f2fa7.png">
